apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-proxy
  namespace: minecraft
spec:
  interval: 1h
  timeout: 15m
  chart:
    spec:
      chart: minecraft-proxy
      version: 3.10.2
      sourceRef:
        kind: HelmRepository
        name: farhoodliquor-minecraft-server-charts
        namespace: flux-system
  values:
    minecraftProxy:
      type: VELOCITY
      velocityVersion: latest







