apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-proxy
  namespace: minecraft
spec:
  interval: 1h
  timeout: 15m
  chart:
    spec:
      chart: minecraft-proxy
      version: 3.9.2
      sourceRef:
        kind: HelmRepository
        name: farhoodliquor-minecraft-server-charts
        namespace: flux-system
  values:
    minecraftProxy:
      type: VELOCITY
      # Velocity selection (these map to the itzg image env vars)
      velocityVersion: latest
      velocityBuildId: latest
      
      # Prevent mc-image-helper from modifying our custom config
      extraEnv:
        SKIP_CONFIG: "true"

      
      # Temporarily disabled to test default config generation
      # config: |
      #   config-version = "2.7"
      #   bind = "0.0.0.0:25577"
      #   motd = "Test"
      #   show-max-players = 500
      #   online-mode = true
      #   player-info-forwarding-mode = "modern"
      #   forwarding-secret-file = "forwarding.secret"
      #
      #   [servers]
      #   lobby = "127.0.0.1:25565"
      #   try = [ "lobby" ]


      # keep the generated file path; the image is already creating it
      velocityForwardingSecretFilePath: /server/forwarding.secret
      # configFilePath: /tmp/velocity-orig.toml

    # Temporarily disabled to test default config generation  
    # initContainers:
    #   - name: copy-config
    #     image: busybox:latest
    #     command: ["sh", "-c", "rm -f /server/velocity.toml && cp /tmp/velocity-init.toml /server/velocity.toml && chmod 644 /server/velocity.toml && echo '=== DEBUG CONFIG ===' && cat /server/velocity.toml && echo '=== END DEBUG ==='"]
    #     volumeMounts:
    #       - name: datadir
    #         mountPath: /server
    #       - name: config
    #         mountPath: /tmp/velocity-init.toml
    #         subPath: config.yml

