apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-proxy
  namespace: minecraft
spec:
  interval: 1h
  timeout: 15m
  chart:
    spec:
      chart: minecraft-proxy
      version: 3.9.1
      sourceRef:
        kind: HelmRepository
        name: farhoodliquor-minecraft-server-charts
        namespace: flux-system
  values:
    minecraftProxy:
      type: VELOCITY
      # Velocity selection (these map to the itzg image env vars)
      velocityVersion: latest
      velocityBuildId: latest

      config: |-
        config-version = "2.7"
        bind = "0.0.0.0:25577"
        motd = "<#09add3>A Velocity Server"
        show-max-players = 500
        online-mode = true

        # THIS is what removes the warning
        player-info-forwarding-mode = "modern"
        forwarding-secret-file = "forwarding.secret"

        [servers]
        lobby = "127.0.0.1:25565"
        try = [ "lobby" ]

        [forced-hosts]

      # keep the generated file path; the image is already creating it
      velocityForwardingSecretFilePath: /server/forwarding.secret

    initContainers:
      - name: copy-config
        image: busybox:latest
        command: ["sh", "-c", "cp /tmp/velocity-init.toml /server/velocity.toml && chown 1000:1000 /server/velocity.toml && echo '=== CONFIG START ===' && cat /server/velocity.toml && echo '=== CONFIG END ==='"]
        volumeMounts:
          - name: datadir
            mountPath: /server
          - name: config
            mountPath: /tmp/velocity-init.toml
            subPath: config.yml
