apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-proxy
  namespace: minecraft
spec:
  interval: 1h
  timeout: 15m
  chart:
    spec:
      chart: minecraft-proxy
      #version: 60.x
      sourceRef:
        kind: HelmRepository
        name: itzg
        namespace: flux-system
  values:
    minecraftProxy:
      type: VELOCITY

      # Velocity selection (these map to the itzg image env vars)
      velocityVersion: 3.3.0
      velocityBuildId: latest

      onlineMode: true
      memory: 512M
      jvmOpts: ""
      jvmXXOpts: ""

      serviceType: LoadBalancer
      externalTrafficPolicy: Local
      configFilePath: /server/config.yml
      plugins: []

      rcon:
        enabled: false

    persistence:
      dataDir:
        enabled: false
        size: 1Gi
