apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft
  namespace: minecraft-farhood-org
spec:
  chart:
    spec:
      chart: minecraft
      version: 4.23.x
      sourceRef:
        kind: HelmRepository
        name: itzg
        namespace: flux-system
  interval: 5m
  timeout: 4m
  releaseName: minecraft
  values: # Values Below
    resources:
      requests:
        memory: "4Gi"
        cpu: "2000m"
      limits:
        memory: "8Gi"
        cpu: "6000m"
    minecraftServer:
      eula: "TRUE"
      version: "LATEST"
      type: "VANILLA"
      whitelist: "cpfarhoodd"
      gameMode: survival
      motd: "Welcome to the hood"
      memory: 3072M
      serviceType: LoadBalancer
      externalTrafficPolicy: Local
    rcon:
      enabled: true
      existingSecret: credentials
      secretKey: rcon-pass
      serviceType: LoadBalancer
      externalTrafficPolicy: Local
    serviceAnnotations:
      metallb.universe.tf/address-pool: reserved-pool
      metallb.universe.tf/loadBalancerIPs: 65.43.40.105
      external-dns.alpha.kubernetes.io/hostname: minecraft.farhood.org
    persistence:
      annotations:
        kustomize.toolkit.fluxcd.io/prune: disabled
      storageClass: "longhorn-perpetual"
      dataDir:
        enabled: true
        Size: 4Gi
        accessModes:
          - ReadWriteOnce