apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft
  namespace: minecraft-farhood-org
spec:
  chart:
    spec:
      chart: minecraft
      version: 4.23.x
      sourceRef:
        kind: HelmRepository
        name: itzg
        namespace: flux-system
  interval: 5m
  timeout: 4m
  releaseName: minecraft
  values: # Values Below
    resources:
      requests:
        memory: "8Gi"
        cpu: "2000m"
      limits:
        memory: "16Gi"
        cpu: "6000m"
    workloadAsStatefulSet: true
    strategyType: RollingUpdate
    minecraftServer:
      eula: "TRUE"
      version: "LATEST"
      type: "PAPER"
      difficulty: hard
      whitelist: ""
      ops: "cpfarhoodd,freakychris"
      maxPlayers: 100
      maxWorldSize: 50000
      gameMode: survival
      motd: "Modded Minecraft Server"
      modUrls:
      - "https://hangarcdn.papermc.io/plugins/William278/HuskHomes/versions/4.7/PAPER/HuskHomes-Paper-4.7.jar"
      - "https://hangarcdn.papermc.io/plugins/Archy/AuraSkills/versions/2.2.4/PAPER/AuraSkills-2.2.4.jar"
      - "https://hangarcdn.papermc.io/plugins/Elliot/LimitlessEnchants/versions/RELEASE-1.0/PAPER/LimitlessEnchants-1.0.jar"
      - "https://hangarcdn.papermc.io/plugins/Aznos/Superenchants/versions/2.6.3/PAPER/SuperEnchants-2.6.3.jar"
      - "https://cdn.modrinth.com/data/OhduvhIc/versions/9hKYZJp8/veinminer-paper-2.2.0.jar"
      - "https://github.com/Jannyboy11/InvSee-plus-plus/releases/download/v0.29.5/InvSee++.jar"
      - "https://github.com/Jannyboy11/InvSee-plus-plus/releases/download/v0.29.5/InvSee++_Clear.jar"
      - "https://github.com/Jannyboy11/InvSee-plus-plus/releases/download/v0.29.5/InvSee++_Give.jar"
      memory: 8192M
      serviceType: LoadBalancer
      externalTrafficPolicy: Local
      rcon:
        enabled: true
        existingSecret: credentials
        secretKey: rcon-pass
        serviceType: LoadBalancer
        externalTrafficPolicy: Local
    serviceAnnotations:
      metallb.universe.tf/address-pool: reserved-pool
      metallb.universe.tf/loadBalancerIPs: 65.43.40.105
      metallb.universe.tf/allow-shared-ip: "minecraft-65.43.40.105"
      external-dns.alpha.kubernetes.io/hostname: minecraft.farhood.org
    rconServiceAnnotations:
      metallb.universe.tf/address-pool: reserved-pool
      metallb.universe.tf/loadBalancerIPs: 65.43.40.105
      metallb.universe.tf/allow-shared-ip: "minecraft-65.43.40.105"
    persistence:
      labels:
        name: minecraft-farhood-org
      annotations:
        kustomize.toolkit.fluxcd.io/prune: disabled
      storageClass: "longhorn-perpetual"
      dataDir:
        enabled: true
        Size: 8Gi
        accessModes:
          - ReadWriteOnce