apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft
  namespace: minecraft-farhood-org
spec:
  chart:
    spec:
      chart: minecraft
      version: 4.23.x
      sourceRef:
        kind: HelmRepository
        name: itzg
        namespace: flux-system
  interval: 5m
  timeout: 4m
  releaseName: minecraft
  values: # Values Below
    resources:
      requests:
        memory: "8Gi"
        cpu: "2000m"
      limits:
        memory: "16Gi"
        cpu: "6000m"
    workloadAsStatefulSet: true
    strategyType: RollingUpdate
    minecraftServer:
      eula: "TRUE"
      version: "LATEST"
      type: "PAPER"
      difficulty: easy
      whitelist: ""
      ops: "cpfarhoodd,freakychris"
      maxPlayers: 100
      maxWorldSize: 50000
      gameMode: survival
      motd: "Welcome to the far side of the hood"
      modUrls:
      - "https://hangarcdn.papermc.io/plugins/William278/HuskHomes/versions/4.7/PAPER/HuskHomes-Paper-4.7.jar"
      memory: 8192M
      serviceType: LoadBalancer
      externalTrafficPolicy: Local
      rcon:
        enabled: true
        existingSecret: credentials
        secretKey: rcon-pass
        serviceType: LoadBalancer
        externalTrafficPolicy: Local
    serviceAnnotations:
      metallb.universe.tf/address-pool: reserved-pool
      metallb.universe.tf/loadBalancerIPs: 65.43.40.105
      metallb.universe.tf/allow-shared-ip: "minecraft-65.43.40.105"
      external-dns.alpha.kubernetes.io/hostname: minecraft.farhood.org
    rconServiceAnnotations:
      metallb.universe.tf/address-pool: reserved-pool
      metallb.universe.tf/loadBalancerIPs: 65.43.40.105
      metallb.universe.tf/allow-shared-ip: "minecraft-65.43.40.105"
    persistence:
      labels:
        name: minecraft-farhood-org
      annotations:
        kustomize.toolkit.fluxcd.io/prune: disabled
      storageClass: "longhorn-perpetual"
      dataDir:
        enabled: true
        Size: 8Gi
        accessModes:
          - ReadWriteOnce