apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft
spec:
  chart:
    spec:
      chart: minecraft
      version: 4.23.x
      sourceRef:
        kind: HelmRepository
        name: itzg
  interval: 15m
  timeout: 5m
  values: # Values Below
    resources:
      requests:
        memory: "8Gi"
        cpu: "2000m"
      limits:
        memory: "16Gi"
        cpu: "6000m"
    workloadAsStatefulSet: true
    strategyType: RollingUpdate
    minecraftServer:
      eula: "TRUE"
      version: "LATEST"
      type: "PAPER"
      difficulty: hard
      whitelist: ""
      ops: "cpfarhoodd,freakychris"
      maxPlayers: 100
      maxWorldSize: 50000
      gameMode: survival
      motd: "Modded Minecraft Server 6"
      modUrls:
      - "https://hangarcdn.papermc.io/plugins/William278/HuskHomes/versions/4.7/PAPER/HuskHomes-Paper-4.7.jar"
      - "https://hangarcdn.papermc.io/plugins/Archy/AuraSkills/versions/2.2.4/PAPER/AuraSkills-2.2.4.jar"
      - "https://cdn.modrinth.com/data/OhduvhIc/versions/9hKYZJp8/veinminer-paper-2.2.0.jar"
      - "https://github.com/Jannyboy11/InvSee-plus-plus/releases/download/v0.29.5/InvSee++.jar"
      - "https://github.com/Jannyboy11/InvSee-plus-plus/releases/download/v0.29.5/InvSee++_Clear.jar"
      - "https://github.com/Jannyboy11/InvSee-plus-plus/releases/download/v0.29.5/InvSee++_Give.jar"
      - "https://cdn.modrinth.com/data/C0XNE0Q2/versions/n4eDmZgc/SimpleCombatLog.jar"
      - "https://cdn.modrinth.com/data/1u6JkXh5/versions/ecqqLKUO/worldedit-bukkit-7.3.8.jar"
      - "https://hangarcdn.papermc.io/plugins/TheNextLvl/Protect/versions/2.1.2/PAPER/protect-2.1.2-all.jar"
      memory: 8192M
      serviceType: LoadBalancer
      externalTrafficPolicy: Local
#      rcon:
#        enabled: true
#        existingSecret: credentials
#        secretKey: rcon-pass
#        serviceType: LoadBalancer
#        externalTrafficPolicy: Local
    serviceAnnotations:
      lbipam.cilium.io/ips: "65.43.40.103"
      lbipam.cilium.io/sharing-key: "minecraft.farh.net"
      external-dns.alpha.kubernetes.io/hostname: minecraft.farh.net
    serviceLabels:
      zone: public
#    rconServiceAnnotations:
#      lbipam.cilium.io/ips: "65.43.40.103"
#      lbipam.cilium.io/sharing-key: "minecraft.farh.net"
#      external-dns.alpha.kubernetes.io/hostname: minecraft.farh.net
    persistence:
      labels:
        name: minecraft
      annotations:
        kustomize.toolkit.fluxcd.io/prune: disabled
      storageClass: "ceph-block"
      dataDir:
        enabled: true
        Size: 8Gi
        accessModes:
          - ReadWriteOnce