apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft
  namespace: minecraft-farhood-org
spec:
  chart:
    spec:
      chart: minecraft
      version: 4.23.x
      sourceRef:
        kind: HelmRepository
        name: itzg
        namespace: flux-system
  interval: 5m
  timeout: 4m
  releaseName: minecraft
  values: # Values Below
    resources:
      requests:
        memory: "2Gi"
        cpu: "1000m"
      limits:
        memory: "4Gi"
        cpu: "4000m"
    minecraftServer:
      eula: "TRUE"
      version: "LATEST"
      type: "VANILLA"
    gameMode: survival
    motd: "Welcome to Minecraft on Kubernetes!"
    memory: 1024M
    serviceType: loadBalancer
    externalTrafficPolicy: local
    persistence:
      annotations: {}
      storageClass: "longhorn-perpetual"
      backupDir:
        enabled: true
        Size: 4Gi
        accessModes:
          - ReadWriteOnce