apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft
  namespace: minecraft-farhood-org
spec:
  chart:
    spec:
      chart: minecraft
      version: 4.23.x
      sourceRef:
        kind: HelmRepository
        name: itzg
        namespace: flux-system
  interval: 5m
  timeout: 4m
  releaseName: minecraft
  values: # Values Below
    resources:
      requests:
        memory: "2Gi"
        cpu: "1000m"
      limits:
        memory: "4Gi"
        cpu: "4000m"
    minecraftServer:
      eula: "TRUE"
      version: "LATEST"
      type: "VANILLA"
      whitelist: "cpfarhoodd"
      gameMode: survival
      motd: "Welcome to the hood"
      memory: 2048M
      serviceAnnotations: "metallb.universe.tf/loadBalancerIPs: 65.43.40.105"
      serviceType: LoadBalancer
      externalTrafficPolicy: Local
    persistence:
      annotations: {}
      storageClass: "longhorn-perpetual"
      backupDir:
        enabled: true
        Size: 4Gi
        accessModes:
          - ReadWriteOnce