apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft
  namespace: minecraft-farhood-org
spec:
  chart:
    spec:
      chart: minecraft
      version: 4.23.x
      sourceRef:
        kind: HelmRepository
        name: itzg
        namespace: flux-system
  interval: 5m
  timeout: 4m
  releaseName: minecraft
  values: # Values Below
    resources:
      requests:
        memory: 1Gi
        cpu: 1000m
    minecraftServer:
      eula: "TRUE"
      version: "LATEST"
      # This can be one of "VANILLA", "FORGE", "SPIGOT", "BUKKIT", "PAPER", "FTBA", "SPONGEVANILLA", "AUTO_CURSEFORGE"
      # https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms
      type: "VANILLA"
    gameMode: survival
    # Message of the Day
    motd: "Welcome to Minecraft on Kubernetes!"
    # If true, enable player-vs-player damage.
    memory: 1024M
