apiVersion: shulkermc.io/v1alpha1
kind: MinecraftServerFleet
metadata:
  name: ${SERVERFLEETNAME}
spec:
  clusterRef:
    name: ${CLUSTERNAME}
  replicas: 1
  template:
    spec:
      resources:
        requests:
          cpu: "100m"
          memory: "4Gi"
        limits:
          memory: "8Gi"
      clusterRef:
        name: ${CLUSTERNAME}
      tags:
        - lobby
      version:
        channel: Paper
        name: '1.21.11'
      config: {}