## Ingress
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pufferpanel
  namespace: minecraft-farhood-org
spec:
  ingressClassName: traefik-internal
  rules:
  - host: pufferpanel.farhood.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name:  pufferpanel
            port:
              number: 8080
              
              
## Service
---
apiVersion: v1
kind: Service
metadata:
   name: pufferpanel
   namespace: minecraft-farhood-org
   labels:
     app: pufferpanel
spec:
  type: ClusterIP
  #clusterIP: None
  ports:
  - port: 8080
  selector:
    app: pufferpanel


## StatefulSet
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pufferpanel
  namespace: minecraft-farhood-org
spec:
  selector:
    matchLabels:
      app: pufferpanel
  serviceName: "pufferpanel"
  replicas: 1
  template:
    metadata:
      labels:
        app: pufferpanel
    spec:
      containers:
      - name: pufferpanel
        image: pufferpanel/pufferpanel:latest
        ports:
        - containerPort: 8080
          name: http-8080
        volumeMounts:
        - name: config
          mountPath: "/config"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: pufferpanel-config


## Volumes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pufferpanel-config
  namespace: minecraft-farhood-org
  labels:
#    name: pufferpanel-config
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-perpetual
  resources:
    requests:
      storage: 8Gi
---
