apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mc-router
  namespace: minecraft
spec:
  interval: 1h
  chart:
    spec:
      chart: mc-router
      version: "1.4.0"
      sourceRef:
        kind: HelmRepository
        name: itzg
        namespace: minecraft
      interval: 1h
  values:
    image:
      repository: git.farh.net/farhoodliquor/mc-router
      tag: proxyservername
      pullPolicy: Always
    fullnameOverride: "mc-router"
    args: ["--in-kube-cluster"]
    minecraftRouter:
      autoScale:
        up:
          enabled: true
        down:
          enabled: true
          after: "15m"
        configObject: ConfigMap
        debug:
          enabled: true
    services:
      minecraft:
        annotations:
          service.cilium.io/forwarding-mode: dsr
          lbipam.cilium.io/ips: "71.150.236.210"
          external-dns.alpha.kubernetes.io/hostname: "mc.farh.net,*.mc.farh.net"
        type: LoadBalancer
        port: 25565
      extraServiceSpec:
        externalTrafficPolicy: Local
  postRenderers:
    - kustomize:
        patches:
          # Pass the in-cluster argument to pickup on annotation
          - target:
              group: apps
              version: v1
              kind: Deployment
            patch: |
              - op: add
                path: /spec/template/spec/containers/0/args
                value:
                  - --in-kube-cluster
          # needed to get an external IP with cilium
          - target:
              group: ""
              version: v1
              kind: Service
            patch: |
              - op: add
                path: /metadata/labels
                value: {}
              - op: add
                path: /metadata/labels/zone
                value: public
          # Add patch permission for StatefulSets (required for scale operations)
          - target:
              group: rbac.authorization.k8s.io
              version: v1
              kind: ClusterRole
              name: mc-router
            patch: |
              - op: add
                path: /rules/1/verbs/-
                value: patch
