apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mc-rlcraft
spec:
  interval: 1h
  chart:
    spec:
      chart: minecraft
      version: "5.0.0"
      sourceRef:
        kind: HelmRepository
        name: itzg
        namespace: minecraft
      interval: 1h
  values:
    image:
      repository: itzg/minecraft-server
      tag: java8

    replicaCount: 1
    workloadAsStatefulSet: true
    strategyType: OnDelete

    resources:
      requests:
        cpu: "4"
        memory: "10Gi"
      limits:
        memory: "12Gi"

    startupProbe:
      enabled: true
      command: ["mc-health"]
      failureThreshold: 60
      periodSeconds: 10

    readinessProbe:
      enabled: true
      command: ["mc-health"]
      periodSeconds: 10
      failureThreshold: 6

    livenessProbe:
      enabled: true
      command: ["mc-health"]
      periodSeconds: 30
      failureThreshold: 3

    minecraftServer:
      type: AUTO_CURSEFORGE
      eula: "TRUE"

      # Player-count target
      maxPlayers: 12

      # Big lever for modded TPS: keep server view-distance <= 8
      viewDistance: 8

      gameMode: survival
      difficulty: easy
      levelType: DEFAULT
      worldSaveName: world
      motd: "Welcome to farh.net RLCraft!"

      # Heap: keep below pod memory to leave native/metaspace headroom.
      # 10G heap inside 12Gi pod is the right shape for ~12 players.
      memory: 10G

      # Java 8 GC tuning (G1) to reduce pause spikes on modded servers.
      # Keep it simple and known-good; avoid exotic flags.
      jvmXXOpts: >-
        -XX:+UseG1GC
        -XX:+ParallelRefProcEnabled
        -XX:MaxGCPauseMillis=200
        -XX:+UnlockExperimentalVMOptions
        -XX:+DisableExplicitGC
        -XX:+AlwaysPreTouch
        -XX:G1NewSizePercent=20
        -XX:G1MaxNewSizePercent=40
        -XX:G1HeapRegionSize=16M
        -XX:G1ReservePercent=20
        -XX:G1HeapWastePercent=5
        -XX:G1MixedGCCountTarget=4
        -XX:InitiatingHeapOccupancyPercent=15
        -XX:G1MixedGCLiveThresholdPercent=90
        -XX:G1RSetUpdatingPauseTimePercent=5
        -XX:SurvivorRatio=32
        -XX:MaxTenuringThreshold=1
        -XX:+PerfDisableSharedMem
        -XX:+UseStringDeduplication

      # Keep empty unless you have a specific reason
      jvmOpts: ""

      ops: ${SERVER_OPS}

      autoCurseForge:
        apiKey:
          existingSecret: "minecraft"
          secretKey: CURSEFORGE_API_KEY
        pageUrl: "https://www.curseforge.com/minecraft/modpacks/rlcraft"

    serviceAnnotations:
      mc-router.itzg.me/externalServerName: "rlcraft.${FQDN}"

    persistence:
      dataDir:
        enabled: true
        size: 64Gi

    podDisruptionBudget:
      enabled: true
      minAvailable: 1