apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mc-bmc-5
spec:
  interval: 1h
  chart:
    spec:
      chart: minecraft
      version: "5.0.0"
      sourceRef:
        kind: HelmRepository
        name: itzg
        namespace: minecraft
      interval: 1h

  values:
    fullnameOverride: "mc-bmc-5"
    image:
      repository: itzg/minecraft-server
      # BMC5 NeoForge is MC 1.21.x, so Java 21
      tag: java21

    replicaCount: 1
    workloadAsStatefulSet: true
    strategyType: OnDelete

    tolerations:
      - key: "farh.net/performance"
        operator: "Equal"
        value: "high"
        effect: "NoSchedule"

    # 12-player sizing for a heavy 1.21 NeoForge pack: avoid CPU throttling and leave native headroom
    resources:
      requests:
        cpu: "4"
        memory: "14Gi"
      limits:
        memory: "18Gi"

    startupProbe:
      enabled: true
      command: ["mc-health"]
      failureThreshold: 180
      periodSeconds: 10
      timeoutSeconds: 5

    readinessProbe:
      enabled: true
      command: ["mc-health"]
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 12

    livenessProbe:
      enabled: true
      command: ["mc-health"]
      initialDelaySeconds: 180
      periodSeconds: 30
      timeoutSeconds: 5
      failureThreshold: 6

    minecraftServer:
      type: AUTO_CURSEFORGE
      eula: "TRUE"

      motd: "Welcome to farh.net Better Minecraft 5!"
      gameMode: survival
      difficulty: easy
      ops: ${SERVER_OPS}
      maxPlayers: 12

      # Biggest practical server win: keep these down for TPS stability
      viewDistance: 6
      simulationDistance: 4

      # Reduce IO stalls during spikes/worldgen
      syncChunkWrites: false

      # Stop the watchdog from killing the server during modded stalls
      maxTickTime: -1

      # Heap sizing: do not set heap == pod memory; leave room for metaspace/native/fs-cache
      memory: 14G

      # Keep -X out of jvmOpts; the chart/image derives it from "memory"
      jvmOpts: >-
        -Djava.awt.headless=true
        -Dfile.encoding=UTF-8

      # Conservative G1 tuning (works fine on Java 21; don’t go exotic)
      jvmXXOpts: >-
        -XX:+UnlockExperimentalVMOptions
        -XX:+UseG1GC
        -XX:+ParallelRefProcEnabled
        -XX:MaxGCPauseMillis=150
        -XX:+DisableExplicitGC
        -XX:+AlwaysPreTouch
        -XX:G1NewSizePercent=20
        -XX:G1MaxNewSizePercent=40
        -XX:G1HeapRegionSize=16M
        -XX:G1ReservePercent=20
        -XX:G1HeapWastePercent=5
        -XX:G1MixedGCCountTarget=4
        -XX:InitiatingHeapOccupancyPercent=15
        -XX:G1MixedGCLiveThresholdPercent=90
        -XX:G1RSetUpdatingPauseTimePercent=5
        -XX:SurvivorRatio=32
        -XX:MaxTenuringThreshold=1
        -XX:+PerfDisableSharedMem

      overrideServerProperties: true

      # Explicit for predictable auth behavior
      onlineMode: true
      enforceSecureProfile: true

      autoCurseForge:
        apiKey:
          existingSecret: "minecraft"
          secretKey: CURSEFORGE_API_KEY
        pageUrl: "https://www.curseforge.com/minecraft/modpacks/better-mc-neoforge-bmc5"

    serviceAnnotations:
      mc-router.itzg.me/externalServerName: "bmc-5,bmc-5.${FQDN}"

    persistence:
      dataDir:
        enabled: true
        existingClaim: "mc-server-data"
        subPath: "/bmc-5/"

    podDisruptionBudget:
      enabled: true
      minAvailable: 1
