apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mc-prom-ii
spec:
  interval: 1h
  chart:
    spec:
      chart: minecraft
      version: "5.0.0"
      sourceRef:
        kind: HelmRepository
        name: itzg
        namespace: minecraft
      interval: 1h

  values:
    image:
      repository: itzg/minecraft-server
      tag: java17

    replicaCount: 1
    workloadAsStatefulSet: true
    strategyType: OnDelete

    # 12-player sizing: avoid CPU throttling + keep memory headroom for native/metaspace/fs-cache
    resources:
      requests:
        cpu: "4"
        memory: "14Gi"
      limits:
        memory: "18Gi"

    # Long modded startups + occasional stalls during world gen
    startupProbe:
      enabled: true
      command: ["mc-health"]
      failureThreshold: 180
      periodSeconds: 10
      timeoutSeconds: 5

    readinessProbe:
      enabled: true
      command: ["mc-health"]
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 12

    livenessProbe:
      enabled: true
      command: ["mc-health"]
      initialDelaySeconds: 180
      periodSeconds: 30
      timeoutSeconds: 5
      failureThreshold: 6

    minecraftServer:
      type: AUTO_CURSEFORGE
      eula: "TRUE"

      # Prominence II is Fabric 1.20.1
      # Keep server chunk + entity cost down for 12 players
      viewDistance: 6
      simulationDistance: 4
      syncChunkWrites: false
      maxTickTime: -1

      difficulty: easy
      gameMode: survival
      motd: "Welcome to farh.net Prominence II!"
      ops: ${SERVER_OPS}

      maxPlayers: 12

      # Heap sizing: do not set heap == pod memory; leave ~1–1.5Gi headroom
      memory: 14G

      # GC: baseline G1 tuning widely used for MC; keep flags conservative
      jvmXXOpts: >-
        -XX:+UseG1GC
        -XX:+ParallelRefProcEnabled
        -XX:MaxGCPauseMillis=150
        -XX:+DisableExplicitGC
        -XX:+AlwaysPreTouch
        -XX:G1NewSizePercent=20
        -XX:G1MaxNewSizePercent=40
        -XX:G1HeapRegionSize=16M
        -XX:G1ReservePercent=20
        -XX:G1HeapWastePercent=5
        -XX:G1MixedGCCountTarget=4
        -XX:InitiatingHeapOccupancyPercent=15
        -XX:G1MixedGCLiveThresholdPercent=90
        -XX:G1RSetUpdatingPauseTimePercent=5
        -XX:SurvivorRatio=32
        -XX:MaxTenuringThreshold=1
        -XX:+PerfDisableSharedMem

      jvmOpts: >-
        -Djava.awt.headless=true
        -Dfile.encoding=UTF-8

      overrideServerProperties: true
      allowNether: true
      pvp: true
      onlineMode: true

      worldSaveName: world
      forceReDownload: false
      removeOldMods: false

      autoCurseForge:
        apiKey:
          existingSecret: "minecraft"
          secretKey: CURSEFORGE_API_KEY
        pageUrl: "https://www.curseforge.com/minecraft/modpacks/prominence-2-hasturian-era"

    serviceAnnotations:
      mc-router.itzg.me/externalServerName: "prom-ii.${FQDN}"

    persistence:
      dataDir:
        enabled: true
        size: 64Gi

    podDisruptionBudget:
      enabled: true
      minAvailable: 1