apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mc-bmc-4
spec:
  interval: 1h
  chart:
    spec:
      chart: minecraft
      version: "5.0.0"
      sourceRef:
        kind: HelmRepository
        name: itzg
        namespace: minecraft
      interval: 1h

  values:
    image:
      repository: itzg/minecraft-server
      # BMC4 is Forge 1.20.1 -> run Java 17 (not 21)
      tag: java17

    replicaCount: 1
    workloadAsStatefulSet: true
    strategyType: OnDelete

    # 12-player sizing for BMC4: keep CPU from throttling, keep memory headroom
    resources:
      requests:
        cpu: "4"
        memory: "12Gi"
      limits:
        memory: "16Gi"

    startupProbe:
      enabled: true
      command: ["mc-health"]
      failureThreshold: 180
      periodSeconds: 10
      timeoutSeconds: 5

    readinessProbe:
      enabled: true
      command: ["mc-health"]
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 12

    livenessProbe:
      enabled: true
      command: ["mc-health"]
      initialDelaySeconds: 180
      periodSeconds: 30
      timeoutSeconds: 5
      failureThreshold: 6

    minecraftServer:
      type: AUTO_CURSEFORGE
      eula: "TRUE"

      motd: "Welcome to farh.net Better Minecraft 4!"
      gameMode: survival
      difficulty: easy
      ops: ${SERVER_OPS}
      maxPlayers: 12

      # Biggest practical server-side wins for modded TPS stability
      viewDistance: 6
      simulationDistance: 4
      syncChunkWrites: false
      maxTickTime: -1

      # Heap: leave headroom for metaspace/native/fs-cache inside 14Gi pod
      memory: 12G

      jvmOpts: >-
        -Djava.awt.headless=true
        -Dfile.encoding=UTF-8

      # Conservative G1 tuning for modded MC; stable on Java 17
      jvmXXOpts: >-
        -XX:+UseG1GC
        -XX:+ParallelRefProcEnabled
        -XX:MaxGCPauseMillis=150
        -XX:+DisableExplicitGC
        -XX:+AlwaysPreTouch
        -XX:G1NewSizePercent=20
        -XX:G1MaxNewSizePercent=40
        -XX:G1HeapRegionSize=16M
        -XX:G1ReservePercent=20
        -XX:G1HeapWastePercent=5
        -XX:G1MixedGCCountTarget=4
        -XX:InitiatingHeapOccupancyPercent=15
        -XX:G1MixedGCLiveThresholdPercent=90
        -XX:G1RSetUpdatingPauseTimePercent=5
        -XX:SurvivorRatio=32
        -XX:MaxTenuringThreshold=1
        -XX:+PerfDisableSharedMem

      overrideServerProperties: true
      onlineMode: true
      enforceSecureProfile: true

      forceReDownload: false
      removeOldMods: false
      worldSaveName: world

      autoCurseForge:
        apiKey:
          existingSecret: "minecraft"
          secretKey: CURSEFORGE_API_KEY
        pageUrl: "https://www.curseforge.com/minecraft/modpacks/better-mc-forge-bmc4"

    serviceAnnotations:
      mc-router.itzg.me/externalServerName: "bmc-4.${FQDN}"

    persistence:
      dataDir:
        enabled: true
        size: 64Gi

    podDisruptionBudget:
      enabled: true
      minAvailable: 1