apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mc-atm-10
spec:
  interval: 1h
  chart:
    spec:
      chart: minecraft
      version: "5.0.0"
      sourceRef:
        kind: HelmRepository
        name: itzg
        namespace: minecraft
      interval: 1h

  values:
    image:
      repository: itzg/minecraft-server
      # ATM10 is NeoForge on Minecraft 1.21/1.21.1 -> Java 21
      tag: java21

    replicaCount: 1
    workloadAsStatefulSet: true
    strategyType: OnDelete

    # 12-player sizing for ATM10: CPU headroom + stable memory (don’t throttle ticks)
    resources:
      requests:
        cpu: "4"
        memory: "14Gi"
      limits:
\        memory: "18Gi"

    startupProbe:
      enabled: true
      command: ["mc-health"]
      failureThreshold: 240
      periodSeconds: 10
      timeoutSeconds: 5

    readinessProbe:
      enabled: true
      command: ["mc-health"]
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 12

    livenessProbe:
      enabled: true
      command: ["mc-health"]
      initialDelaySeconds: 180
      periodSeconds: 30
      timeoutSeconds: 5
      failureThreshold: 6

    minecraftServer:
      type: AUTO_CURSEFORGE
      eula: "TRUE"

      motd: "Welcome to farh.net All the Mods 10!"
      gameMode: survival
      difficulty: easy
      ops: ${SERVER_OPS}
      maxPlayers: 12

      # Biggest server-side wins (TPS stability)
      viewDistance: 6
      simulationDistance: 4
      syncChunkWrites: false
      maxTickTime: -1

      # Heap: leave headroom for native/metaspace/fs-cache in a 16Gi pod
      memory: 14G

      # Keep -Xms/-Xmx out of here; the chart/image sets heap from "memory"
      jvmOpts: >-
        -Djava.awt.headless=true
        -Dfile.encoding=UTF-8

      # Conservative G1 tuning (Java 21)
      jvmXXOpts: >-
        -XX:+UseG1GC
        -XX:+ParallelRefProcEnabled
        -XX:MaxGCPauseMillis=150
        -XX:+DisableExplicitGC
        -XX:+AlwaysPreTouch
        -XX:G1NewSizePercent=20
        -XX:G1MaxNewSizePercent=40
        -XX:G1HeapRegionSize=16M
        -XX:G1ReservePercent=20
        -XX:G1HeapWastePercent=5
        -XX:G1MixedGCCountTarget=4
        -XX:InitiatingHeapOccupancyPercent=15
        -XX:G1MixedGCLiveThresholdPercent=90
        -XX:G1RSetUpdatingPauseTimePercent=5
        -XX:SurvivorRatio=32
        -XX:MaxTenuringThreshold=1
        -XX:+PerfDisableSharedMem

      overrideServerProperties: true
      onlineMode: true
      enforceSecureProfile: true

      forceReDownload: false
      removeOldMods: false
      worldSaveName: world

      autoCurseForge:
        apiKey:
          existingSecret: "minecraft"
          secretKey: CURSEFORGE_API_KEY
        pageUrl: "https://www.curseforge.com/minecraft/modpacks/all-the-mods-10"

    serviceAnnotations:
      mc-router.itzg.me/externalServerName: "atm-10.${FQDN}"

    persistence:
      dataDir:
        enabled: true
        size: 64Gi

    podDisruptionBudget:
      enabled: true
      minAvailable: 1