apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mc-bmc-4
  namespace: minecraft
spec:
  interval: 1h
  chart:
    spec:
      chart: minecraft
      version: "5.0.0"
      sourceRef:
        kind: HelmRepository
        name: itzg
        namespace: minecraft
      interval: 1h

  values:
    image:
      repository: itzg/minecraft-server
      # BMC4 = Forge 1.20.1 -> Java 17
      tag: java17

    replicaCount: 1
    workloadAsStatefulSet: true
    strategyType: OnDelete

    tolerations:
      - key: "farh.net/performance"
        operator: "Equal"
        value: "high"
        effect: "NoSchedule"

    resources:
      requests:
        cpu: "4"
        memory: "12Gi"
      limits:
        memory: "16Gi"

    startupProbe:
      enabled: true
      command: ["mc-health"]
      failureThreshold: 180
      periodSeconds: 10
      timeoutSeconds: 5

    readinessProbe:
      enabled: true
      command: ["mc-health"]
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 12

    livenessProbe:
      enabled: true
      command: ["mc-health"]
      initialDelaySeconds: 180
      periodSeconds: 30
      timeoutSeconds: 5
      failureThreshold: 6

    minecraftServer:
      type: AUTO_CURSEFORGE
      eula: "TRUE"

      motd: "Welcome to farh.net Better Minecraft 4!"
      gameMode: survival
      difficulty: easy
      ops: ${SERVER_OPS}
      maxPlayers: 12

      viewDistance: 6
      simulationDistance: 4
      syncChunkWrites: false
      maxTickTime: -1

      memory: 12G

      jvmOpts: >-
        -Djava.awt.headless=true
        -Dfile.encoding=UTF-8

      jvmXXOpts: >-
        -XX:+UnlockExperimentalVMOptions
        -XX:+UseG1GC
        -XX:+ParallelRefProcEnabled
        -XX:MaxGCPauseMillis=150
        -XX:+DisableExplicitGC
        -XX:+AlwaysPreTouch
        -XX:G1NewSizePercent=20
        -XX:G1MaxNewSizePercent=40
        -XX:G1HeapRegionSize=16M
        -XX:G1ReservePercent=20
        -XX:G1HeapWastePercent=5
        -XX:G1MixedGCCountTarget=4
        -XX:InitiatingHeapOccupancyPercent=15
        -XX:G1MixedGCLiveThresholdPercent=90
        -XX:G1RSetUpdatingPauseTimePercent=5
        -XX:SurvivorRatio=32
        -XX:MaxTenuringThreshold=1
        -XX:+PerfDisableSharedMem

      overrideServerProperties: true
      onlineMode: true
      enforceSecureProfile: true

      forceReDownload: false
      removeOldMods: false
      worldSaveName: world

      autoCurseForge:
        apiKey:
          existingSecret: "minecraft"
          secretKey: CURSEFORGE_API_KEY
        pageUrl: "https://www.curseforge.com/minecraft/modpacks/better-mc-forge-bmc4"

    # Add Wakes + its required deps (+ VS + KotlinForForge required by VS)
    # MODS supports direct JAR URLs.  [oai_citation:4‡Minecraft Server on Docker](https://docker-minecraft-server.readthedocs.io/en/latest/mods-and-plugins/?utm_source=chatgpt.com)
    extraEnv:
      MODS: |-
        https://cdn.modrinth.com/data/E0SdeAoH/versions/zP45vj8T/wakes-1.20.1-Forge-1.0.8.jar
        https://cdn.modrinth.com/data/vuNeeDyl/versions/VX4fjmf1/alekiNiftyShips-FORGE-1.20.1-1.0.14.jar
        https://cdn.modrinth.com/data/EO8aSHxh/versions/gkwkGpv4/eureka-1201-1.6.1.jar
        https://cdn.modrinth.com/data/V5ujR2yw/versions/leF4D8yr/valkyrienskies-120-2.4.9.jar
        https://cdn.modrinth.com/data/ordsPcFz/versions/hmeyC41q/kotlinforforge-4.11.0-all.jar

    serviceAnnotations:
      mc-router.itzg.me/externalServerName: "bmc-4,bmc-4.${FQDN}"

    persistence:
      dataDir:
        enabled: true
        size: 64Gi

    podDisruptionBudget:
      enabled: true
      minAvailable: 1
