apiVersion: v1
kind: Service
metadata:
  name: picolimbo
  labels:
    app.kubernetes.io/name: minecraft
    app.kubernetes.io/instance: picolimbo
  annotations:
    mc-router.itzg.me/defaultServer: "true"
spec:
  type: ClusterIP
  ports:
  - port: 25565
    targetPort: 25565
    protocol: TCP
    name: minecraft
  selector:
    app: picolimbo