apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-server-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256Gi
  storageClassName: ceph-filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
