apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: minecraft-db
spec:
  rootPasswordSecretKeyRef:
    name: minecraft-db-rootpw
    key: password
  replicas: 3
  replication:
    enabled: true
    primary:
      autoFailover: true
  storage:
    size: 16Gi
  primaryService:
    type: ClusterIP
