apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: pterodactyl
spec:
  replicas: 3
  args:
    - --proactor_threads=2
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 512Mi
