apiVersion: v1
kind: Secret
metadata:
  name: ctrlpanelgg
type: Opaque
stringData:
  MAIL_PASSWORD: ${CTRLPANELGG_MAIL_PW}
  DB_PASSWORD: ${CTRLPANELGG_DB_USERPW}
  REDIS_PASSWORD: ${CTRLPANELGG_REDIS_PW}
  ADMIN_PASSWORD: ${CTRLPANELGG_ADMIN_PASSWORD}
