apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: atm10
  labels:
    app.kubernetes.io/name: minecraft
    app.kubernetes.io/instance: atm10
spec:
  serviceName: atm10
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: atm10
  template:
    metadata:
      labels:
        app.kubernetes.io/name: atm10
    spec:
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 120
      priorityClassName: high-priority
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
      securityContext:
        fsGroup: 1000
      containers:
        - name: minecraft
          image: itzg/minecraft-server:java21
          ports:
            - name: minecraft
              containerPort: 25565
              protocol: TCP
          env:
            - name: EULA
              value: "TRUE"
            # Use TYPE/VERSION or MODPACK_PLATFORM not both
            #- name: TYPE
            #  value: "FABRIC"
            #- name: VERSION
            #  value: "1.20.1"
            - name: MEMORY
              value: "16G"
            - name: DEBUG
              value: "FALSE"
            - name: MOTD
              value: "Get a fucking job"
            - name: OPS
              value: "cpfarhoodd,freakychris"
            - name: USE_AIKAR_FLAGS
              value: "true"
            - name: MODPACK_PLATFORM
              value: "AUTO_CURSEFORGE"
            - name: CF_API_KEY
              value: ${CURSEFORGE_API_KEY}
            - name: CF_PAGE_URL
              value: "https://www.curseforge.com/minecraft/modpacks/all-the-mods-10"
          volumeMounts:
            - name: data
              mountPath: /data

          startupProbe:
            tcpSocket:
              port: 25565
            periodSeconds: 10
            failureThreshold: 60

          readinessProbe:
            tcpSocket:
              port: 25565
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6

          livenessProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 90
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3

          resources:
            requests:
              cpu: "1"
              memory: "12Gi"
            limits:
              memory: "15Gi"

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 60Gi
