apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mc-proxy
spec:
  interval: 1h
  chart:
    spec:
      chart: minecraft-proxy
      #version: "5.0.0"
      sourceRef:
        kind: HelmRepository
        name: itzg
        namespace: minecraft
      interval: 1h

  values:
    serviceAnnotations:
      service.cilium.io/forwarding-mode: dsr
      lbipam.cilium.io/ips: "71.150.236.210"
      external-dns.alpha.kubernetes.io/hostname: "mc.farh.net,*.mc.farh.net"
    minecraftProxy:
      # This can be one of "BUNGEECORD", "WATERFALL", "VELOCITY", "CUSTOM"
      type: VELOCITY
      # If type is set to VELOCITY, download and run this version of Velocity
      velocityVersion: 3.3.0
      # Check accounts against Minecraft account service.
      onlineMode: true
      # A list of .jar URLs to download into the plugins folder.
      plugins: []
      # If you adjust this, you may need to adjust resources.requests above to match.
      memory: 512M
      # General JVM options to be passed to the Minecraft server invocation
      jvmOpts: ""
      # Options like -X that need to proceed general JVM options
      jvmXXOpts: ""
      serviceType: ClusterIP
      # This can be set to the contents of your config file (only works with yaml currently)
      config: |
        bind = "0.0.0.0:25577"
        motd = "Welcome to farh.net Minecraft Fleet!"
        show-max-players = 12
        player-info-forwarding-mode = "modern"

  postRenderers:
    - kustomize:
        patches:
          - target:
              group: ""
              version: v1
              kind: Service
            patch: |
              - op: add
                path: /metadata/labels
                value: {}
              - op: add
                path: /metadata/labels/zone
                value: public