apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mc-proxy
spec:
  interval: 1h
  chart:
    spec:
      chart: minecraft-proxy
      #version: "5.0.0"
      sourceRef:
        kind: HelmRepository
        name: itzg
        namespace: minecraft
      interval: 1h

  values:
    serviceType: LoadBalancer
    serviceAnnotations:
      service.cilium.io/forwarding-mode: dsr
      lbipam.cilium.io/ips: "71.150.236.210"
      external-dns.alpha.kubernetes.io/hostname: "mc.farh.net,*.mc.farh.net"
    minecraftProxy:
      # This can be one of "BUNGEECORD", "WATERFALL", "VELOCITY", "CUSTOM"
      type: VELOCITY
      # If type is set to VELOCITY, download and run this version of Velocity
      velocityVersion: 3.4.0
      # Check accounts against Minecraft account service.
      onlineMode: true
      # A list of .jar URLs to download into the plugins folder.
      plugins: []
      # If you adjust this, you may need to adjust resources.requests above to match.
      memory: 512M
      # General JVM options to be passed to the Minecraft server invocation
      jvmOpts: ""
      # Options like -X that need to proceed general JVM options
      jvmXXOpts: ""
      serviceType: ClusterIP
      # This can be set to the contents of your config file (only works with yaml currently)
      velocityForwardingSecret: "${VELOCITY_FWD_SECRET}"
      config: |
        config-version = "2.7"

        bind = "0.0.0.0:25565"
        motd = "farh.net Minecraft"
        show-max-players = 12

        online-mode = true
        force-key-authentication = true
        prevent-client-proxy-connections = false

        # Preserve original client hostname/IP/UUID to downstream (mc-router + backend)
        player-info-forwarding-mode = "modern"

        # --------------------------------------------------
        # BACKEND SERVERS
        # All gameplay entries point at mc-router.
        # mc-router routes based on the ORIGINAL hostname.
        # --------------------------------------------------
        [servers]
        # Gameplay (routed by mc-router)
        rlcraft = "mc-router:25565"
        bmc-4 = "mc-router:25565"
        bmc-5 = "mc-router:25565"
        atm-10 = "mc-router:25565"
        prom-ii = "mc-router:25565"
        cursed-walking = "mc-router:25565"

        # Always-on fallback servers (direct)
        lobby = "lobby:25565"
        limbo = "picolimbo:25565"

        # --------------------------------------------------
        # DEFAULT / FALLBACK CONNECT ORDER
        # Used when NO forced-host matches (e.g. mc.farh.net or raw IP)
        # --------------------------------------------------
        try = [
          "lobby",
          "limbo"
        ]

        # --------------------------------------------------
        # HOSTNAME-BASED ROUTING (Minecraft handshake hostname)
        # Client hostnames map to the server entries above (which all go to mc-router).
        # --------------------------------------------------
        [forced-hosts]
        "rlcraft.mc.farh.net" = ["rlcraft"]
        "bmc-4.mc.farh.net" = ["bmc-4"]
        "bmc-5.mc.farh.net" = ["bmc-5"]
        "atm-10.mc.farh.net" = ["atm-10"]
        "prom-ii.mc.farh.net" = ["prom-ii"]
        "cursed-walking.mc.farh.net" = ["cursed-walking"]

        # Intentionally NOT listed:
        # - "mc.farh.net"
        # - direct IP connects
        # Those follow `try` -> lobby -> limbo

        # --------------------------------------------------
        # ADVANCED
        # --------------------------------------------------
        [advanced]
        login-ratelimit = 3000
        compression-threshold = 256
        compression-level = -1

  postRenderers:
    - kustomize:
        patches:
          - target:
              group: ""
              version: v1
              kind: Service
            patch: |
              - op: add
                path: /metadata/labels
                value: {}
              - op: add
                path: /metadata/labels/zone
                value: public
