apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mc-proxy
spec:
  interval: 1h
  chart:
    spec:
      chart: minecraft-proxy
      #version: "5.0.0"
      sourceRef:
        kind: HelmRepository
        name: farhoodliquor
        namespace: minecraft
      interval: 1h
  values:
    fullname: "mc-proxy"
    serviceAnnotations:
      service.cilium.io/forwarding-mode: dsr
      mc-router.itzg.me/defaultServer: "proxy"
    resources:
      requests:
        memory: "512Mi"
        cpu: "100m"
      limits:
        memory: "1024Mi"
    minecraftProxy:
      serviceType: ClusterIP
      # This can be one of "BUNGEECORD", "WATERFALL", "VELOCITY", "CUSTOM"
      type: VELOCITY
      # If type is set to VELOCITY, download and run this version of Velocity
      velocityVersion: 3.4.0
      # Check accounts against Minecraft account service.
      onlineMode: true
      # A list of .jar URLs to download into the plugins folder.
      plugins:
        - "https://github.com/plan-player-analytics/Plan/releases/download/5.6.2965/Plan-5.6-build-2965.jar"
      # If you adjust this, you may need to adjust resources.requests above to match.
      memory: 512M
      # General JVM options to be passed to the Minecraft server invocation
      jvmOpts: ""
      # Options like -X that need to proceed general JVM options
      jvmXXOpts: ""
      # This can be set to the contents of your config file (only works with yaml currently)
      velocityForwardingSecret: "${VELOCITY_FWD_SECRET}"
      velocityForwardingSecretFilePath: /server/forwarding.secret
      # extraPorts:
      #   - name: plan
      #     containerPort: 8804
      #     protocol: TCP
      #     service:
      #       enabled: true
      #       embedded: false
      #       annotations: {}
      #       type: ClusterIP
      #       port: 8804
      #     ingress:
      #       ingressClassName: traefik-external
      #       enabled: true
      #       annotations:
      #         cert-manager.io/cluster-issuer: letsencrypt
      #         external-dns.alpha.kubernetes.io/hostname: plan.${FQDN}
      #       hosts:
      #         - name: plan.${FQDN}
      #           path: /
      #       tls:
      #         - secretName: plan-tls
      #           hosts:
      #             - plan.${FQDN}
      configFilePath: /server/velocity.toml
      config: |
        config-version = "2.7"
        bind = "0.0.0.0:25577"
        motd = "farh.net Minecraft"
        show-max-players = 12
        online-mode = true
        announce-forge = true
        force-key-authentication = true
        prevent-client-proxy-connections = false
        # Preserve original client hostname/IP/UUID to downstream (mc-router + backend)
        player-info-forwarding-mode = "modern"
        forwarding-secret-file = "/server/forwarding.secret"
        #
        # --------------------------------------------------
        # BACKEND SERVERS
        # All gameplay entries point at mc-router.
        # mc-router routes based on the ORIGINAL hostname.
        # --------------------------------------------------
        #
        [servers]
        # Gameplay (routed by mc-router)
        rochester = "mc-rochester:25565"
        detroit = "mc-detroit:25565"
        rlcraft = "mc-rlcraft:25565"
        bmc-4 = "mc-bmc:25565"
        bmc-5 = "mc-bmc-5:25565"
        atm-10 = "mc-atm-10:25565"
        prominence-2 = "mc-prominence-2:25565"
        cursed-walking = "mc-cursed-walking:25565"
        # Always-on fallback servers (direct)
        lobby = "mc-lobby:25565"
        limbo = "mc-limbo:25565"
        #
        # --------------------------------------------------
        # DEFAULT / FALLBACK CONNECT ORDER
        # Used when NO forced-host matches (e.g. mc.farh.net or raw IP)
        # --------------------------------------------------
        try = [
          "rochester",
          "lobby",
          "limbo"
        ]
        #
        # --------------------------------------------------
        # HOSTNAME-BASED ROUTING (Minecraft handshake hostname)
        # Client hostnames map to the server entries above (which all go to mc-router).
        # --------------------------------------------------
        [forced-hosts]
        "rochester.${FQDN}" = ["rochester"]
        "detroit.${FQDN}" = ["detroit"]
        "rlcraft.${FQDN}" = ["rlcraft"]
        "bmc-4.${FQDN}" = ["bmc-4"]
        "bmc-5.${FQDN}" = ["bmc-5"]
        "atm-10.${FQDN}" = ["atm-10"]
        "prominence-2.${FQDN}" = ["prominence-2"]
        "cursed-walking.${FQDN}" = ["cursed-walking"]
        #
        # --------------------------------------------------
        # ADVANCED
        # --------------------------------------------------
        [advanced]
        login-ratelimit = 3000
        compression-threshold = 256
        compression-level = -1
        #
    persistence:
      dataDir:
        enabled: true
        Size: 1Gi
  postRenderers:
    - kustomize:
        patches:
          - target:
              group: ""
              version: v1
              kind: Service
            patch: |
              - op: add
                path: /metadata/labels
                value: {}
              - op: add
                path: /metadata/labels/zone
                value: public
