apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: shulker-operator
  namespace: shulker-operator
spec:
  interval: 1h
  chart:
    spec:
      chart: shulker-operator
      version: "0.14.7"
      sourceRef:
        kind: HelmRepository
        name: farhoodliquor
        namespace: flux-system
      interval: 15m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
